name: Update Notion with Series Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread requests notion-client

      - name: Run script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python update_notion.py
